<?php

$config = [
    'appellations' => [
      'AOP Béarn',
      'AOP Bergerac',
      'AOP Bordeaux',
      'AOP Bordeaux supérieur',
      'AOP Brulhois',
      'AOP Buzet',
      'AOP Cahors',
      'AOP Coteaux du Quercy',
      'AOP Côtes de Duras',
      'AOP Côtes de Millau',
      'AOP Côtes du Marmandais',
      'AOP Entraygues - Le Fel',
      'AOP Estaing',
      'AOP Fronton',
      'AOP Gaillac',
      'AOP Hors Sud-ouest',
      'AOP Irouleguy',
      'AOP Jurançon',
      'AOP Madiran',
      'AOP Marcillac',
      'AOP Pacherenc du Vic Bilh',
      'AOP Saint-Mont',
      'AOP Saint-Sardos',
      'AOP Tursan',
      'IGP Agenais',
      'IGP Ariége',
      'IGP Atlantique',
      'IGP Aveyron',
      'IGP Comté Tolosan',
      'IGP Coteaux de Glanes',
      'IGP Côtes de Gascogne',
      'IGP Côtes du Lot',
      'IGP Côtes du Tarn',
      'IGP Gers',
      'IGP Hors Sud-ouest',
      'IGP Landes',
      'IGP Lavilledieu',
      'IGP Thézac-Perricard'
    ],
    'couleurs' => [
      'Blanc',
      'Blanc doux',
      'Blanc moelleux',
      'Blanc sec',
      'Rosé',
      'Rouge',
      'Surmûris Blanc',
    ],
    'qrcode' => [
        'color' => "#000000",
        'logo'  => __DIR__.'/../web/images/ivso.svg',
    ],
    'theme' => getenv('THEME') ?: 'nutrivin',
//    'db_pdo' => 'couchdb:http://admin:admin@127.0.0.1:5984/nutrivin_test',
//    'admin_user' => 'userid',
];
